INSERT INTO resources (user_id, title, description, url, media_url, is_video, category_id, is_private)
VALUES
  (1, 'Learn with Us– Make Art', 'bicycle rights palo santo swag yr hell of taxidermy vinyl. Chambray actually pug fashion axe affogato banjo seitan. Paleo polaroid artisan pop-up echo park letterpress pabst waistcoat PBR&B wolf. Actually sartorial artisan coloring book.', 'https://www.letsmakeart.com/pages/learn-with-us', 'https://api.screenshotmachine.com?key=506e0f&url=https://www.letsmakeart.com/pages/learn-with-us&dimension=1024x768&zoom=200', false, 1, false),
  (1, '40+ Easy Recipes for New Cooks | Kitchn', 'Taxidermy dreamcatcher flannel gastropub venmo plaid 3 wolf moon air plant sustainable tousled beard blue bottle artisan. Kale chips put a bird on it affogato fixie. Gochujang letterpress selfies', 'https://www.thekitchn.com/simple-recipes-for-new-cooks-23017308', 'https://api.screenshotmachine.com?key=506e0f&url=https://www.thekitchn.com/simple-recipes-for-new-cooks-23017308&dimension=1024x768&zoom=200', false, 2, false),
  (2, 'Photoshop Tutorial for Beginners 2021', 'Chillwave tumblr ennui cardigan cray poutine retro snackwave hexagon dreamcatcher drinking vinegar ethical fingerstache mixtape gochujang. Kombucha lo-fi bespoke jianbing hot chicken meggings', 'https://www.youtube.com/watch?v=61mkx_OV61s', 'https://www.youtube.com/embed/61mkx_OV61s?feature=oembed', true, 3, false),
  (2, 'How to Buy & Sell Bitcoin/Crypto via P2P on Binance for Beginners', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu ipsum felis. Morbi ut dapibus odio. Morbi non sollicitudin risus. Quisque imperdiet finibus ante', 'https://cyberbump.net/how-to-buy-sell-bitcoin-crypto-via-p2p-on-binance-for-beginners-tutorial-2/', 'https://api.screenshotmachine.com?key=506e0f&url=https://cyberbump.net/how-to-buy-sell-bitcoin-crypto-via-p2p-on-binance-for-beginners-tutorial-2/&dimension=1024x768&zoom=200', false, 5, false),
  (3, 'Sunflowers: How to Plant, Grow, and Care for Sunflower Plants', 'Vivamus viverra ante et tortor pulvinar, et ultricies mauris pulvinar. Nulla eu metus tincidunt, rutrum sem in, gravida eros. Integer a lorem ut sem blandit porttitor.', 'https://www.almanac.com/plant/sunflowers', 'https://api.screenshotmachine.com?key=506e0f&url=https://www.almanac.com/plant/sunflowers&dimension=1024x768&zoom=200', false, 5, false),
  (3, 'How to Walk', 'Phasellus leo tortor, tempor non eros vitae, aliquam mollis quam. Fusce eleifend tellus vel fermentum pretium. Proin elementum tempus justo, sed rhoncus velit. Quisque dictum posuere ex at cursus. Nunc ac posuere tortor.', 'https://www.wikihow.com/Walk', 'https://api.screenshotmachine.com?key=506e0f&url=https://www.wikihow.com/Walk&dimension=1024x768&zoom=200', false, 6, false),
  (4, 'Best way to learn Korean', 'Fusce mollis accumsan lorem, vitae eleifend quam ultrices ac. Donec volutpat risus sed orci efficitur consequat. Vestibulum ullamcorper aliquet ipsum, vitae facilisis ex molestie et. Sed leo lacus, hendreritlus', 'https://en.duolingo.com/course/ko/en/Learn-Korean', 'https://api.screenshotmachine.com?key=506e0f&url=https://en.duolingo.com/course/ko/en/Learn-Korean&dimension=1024x768&zoom=200', false, 7, false),
  (4, 'marketing digital', 'urna. Donec diam erat, molestie id magna in, faucibus ultricies massa. Suspendisse varius ac elit nec lacinia. Praesent augue tortor, rutrum et tristique volutpat, tincidunt non lacus. Morbi est nisi, dignissim a sapien.', 'https://www.dailymotion.com/video/x2epmek', 'https://www.dailymotion.com/embed/video/x2epmek', true, 8, false),
  (5, 'Audio: Drums Tutorial', 'Fusce dignissim bibendum mauris, vitae rutrum nisl auctor non. Integer suscipit, nibh nec porta sollicitudin, tellus quam tempus libero, ac sagittis est ipsum vitae metus. Suspendisse non aliquet risus.', 'https://vimeo.com/167175768', 'https://player.vimeo.com/video/167175768?h=06af5524c6&amp;app_id=122963', true, 9, false),
  (5, 'Lighthouse Labs Week 1 - join concepts', 'Nulla luctus bibendum cursus. at mi suscipit ac. Etiam ullamcorper nibh arcu, et blandit eros venenatis ut. Maecenas eget diam consequat, ullamcorper tortor et, dignissim velit.', 'https://gist.github.com/kvirani/7f98a6a8c067e1ff8d754f2289c6a382', 'https://api.screenshotmachine.com?key=506e0f&url=https://gist.github.com/kvirani/', false, 10, false)
 ;
