INSERT INTO comments (user_id, resource_id, comment)
VALUES
  (1, 10, 'Ramps man bun actually'),
  (1, 9, 'vice VHS swag semiotics hexagon YOLO blog vinyl 3 wolf moon kitsch'),
  (2, 10, 'Nulla fanny pack unicorn cray quis swag in beard'),
  (2, 9, 'Pop-up cardigan unicorn, shabby chic incididunt leggings'),
  (2, 8, 'Occaecat authentic crucifix vice ugh dolore sunt irure synth bespoke vaporware mlkshk umami'),
  (3, 9, 'Austin cliche dolore aliquip ut shoreditch gochujang'),
  (3, 10, 'Reprehenderit chillwave messenger bag sartorial. '),
  (3, 7, 'Humblebrag locavore meh migas consequat jean shorts hell of '),
  (4, 8, 'quis glossier air plant fanny pack roof party. Letterpress narwhal c'),
  (4, 9, 'do, deep v williamsburg literally hexagon venmo exercpack meditation eiusmod paleo officia aliqua man braid nulla you proba'),
  (4, 10, 'Letterpress 3 wolf moon polaroid.'),
  (4, 6, 'Mustache elit shaman'),
  (4, 7, 'before they sold out '),
  (5, 8, 'blecore reprehenderit 3 wolf moon ethical. William'),
  (5, 9, 'ut raclette in palo santo 90s gluten-free mumblecore '),
  (5, 1, 'Wolf letterpress taiyaki'),
  (5, 2, 'cupidatat coloring book narwhal pork belly aute et bicycle rights'),
  (1, 6, 'roof party locavore farm-to-table. Ut marfa palo santo pork belly 3'),
  (2, 2, 'moon fam. Lomo anim pariatur, selvage art party occupy post-ironic artisan craft beer ut 90'),
    (3, 5, 'aesthetic. Kitsch art party pinterest put a bird on it, lomo sunt cupidatat laboris adipisicing occaecat meh lyft biodiesel helvetica try-hard'),
  (4, 4, 'atch semiotics lomo lyft readymade. Viral kitsch ramps, activated charcoal raclette gochujang labore non consectetur cornhole '),
  (5, 5, 'ixtape et, vexillologist pitchfork blog hashtag taiyaki freegan intelligentsia fixie '),
  (1, 4, 'Williamsburg mixtape ut raclette in palo santo'),
  (2, 10, 'Letterpress 3 wolf moon polaroid, listicle viral pickled jianbing dreamcatcher c'),
  (3, 3, 'party. Letterpress narwhal commodo, deep v williamsburg literally hexa'),
  (4, 1, 'shorts hell of quis glossier air plant fanny pack roof'),
  (5, 7, 'bag four dollar toast tbh deep v vaporware. Wolf letterpress taiyaki'),
  (1, 5, 'locavore farm-to-table. Ut marfa palo santo pork belly 3 wolf moon fam'),
  (2, 6, 'occupy post-ironic artisan craft beer ut 90')
 ;
