DROP TABLE IF EXISTS likes CASCADE;

CREATE TABLE likes
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) DELETE ON CASCADE,
  resource_id INTEGER REFERENCES resources(id) DELETE ON CASCADE
);

